import { RiskBadge, Badge } from "@/components/ui/Badge";
import { Card, CardHeader, CardTitle } from "@/components/ui/Card";
import { Alert } from "@/components/ui/Alert";
import type { ITriageSession } from "@/types";
import { format } from "date-fns";

// ─────────────────────────────────────────────────────────────────
// ReportCard — Patient-facing triage report summary
// CRITICAL: Patients see recommendations only, NOT raw condition names
// ─────────────────────────────────────────────────────────────────

interface ReportCardProps {
  session: ITriageSession;
}

export function ReportCard({ session }: ReportCardProps) {
  const hasEmergencyFlags = session.safetyFlags?.some(
    (f) => f.severity === "emergency"
  );

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <Card>
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-lg font-bold text-gray-900">Your Pre-Consultation Summary</h2>
            <p className="mt-1 text-sm text-gray-500">
              {format(new Date(session.createdAt), "PPP 'at' p")}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <RiskBadge level={session.riskLevel} />
            <Badge
              variant={
                session.status === "validated"
                  ? "success"
                  : session.status === "completed"
                  ? "info"
                  : "default"
              }
            >
              {session.status === "validated"
                ? "Clinician Reviewed"
                : session.status === "completed"
                ? "Pending Review"
                : "In Progress"}
            </Badge>
          </div>
        </div>
      </Card>

      {/* Emergency flags */}
      {hasEmergencyFlags && (
        <Alert variant="emergency" title="Urgent Safety Notice">
          Your assessment flagged symptoms that may require prompt medical
          attention. Please seek emergency care if symptoms worsen.
        </Alert>
      )}

      {/* Chief complaint */}
      <Card>
        <CardHeader>
          <CardTitle>Main Concern</CardTitle>
        </CardHeader>
        <p className="text-gray-700">{session.chiefComplaint}</p>
      </Card>

      {/* Safety flags */}
      {session.safetyFlags?.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Attention Points</CardTitle>
          </CardHeader>
          <ul className="space-y-2">
            {session.safetyFlags.map((flag, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span
                  className={`mt-0.5 h-2 w-2 rounded-full flex-shrink-0 ${
                    flag.severity === "emergency"
                      ? "bg-red-500"
                      : flag.severity === "urgent"
                      ? "bg-orange-500"
                      : "bg-yellow-500"
                  }`}
                />
                <span className="text-sm text-gray-700">{flag.flag}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* Recommendations */}
      {session.recommendations?.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Recommendations</CardTitle>
          </CardHeader>
          <ul className="space-y-2">
            {session.recommendations.map((rec, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="mt-1 text-blue-500">→</span>
                <span className="text-sm text-gray-700">{rec}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* Clinician review note (if validated) */}
      {session.doctorValidation && (
        <Card className="border-green-200 bg-green-50">
          <CardHeader>
            <CardTitle className="text-green-800">Clinician Review</CardTitle>
          </CardHeader>
          <div className="space-y-2">
            <div>
              <p className="text-xs font-medium text-gray-500 uppercase tracking-wide">Reviewed by</p>
              <p className="text-gray-900">
                {session.doctorValidation.doctorName} •{" "}
                {format(new Date(session.doctorValidation.validatedAt), "PPp")}
              </p>
            </div>
            {session.doctorValidation.notes && (
              <div>
                <p className="text-xs font-medium text-gray-500 uppercase tracking-wide">Notes</p>
                <p className="text-sm text-gray-700">{session.doctorValidation.notes}</p>
              </div>
            )}
          </div>
        </Card>
      )}

      {/* Disclaimer */}
      <Alert variant="info" title="Important Notice">
        This summary was generated by an AI assistant to help your clinician
        understand your symptoms. It is <strong>not a medical diagnosis</strong>.
        Please consult a healthcare professional for proper evaluation and advice.
      </Alert>
    </div>
  );
}
